const orgData = [
  {
    "id": 100,
    "parentId": null,
    "name": "Prabhakar",
    "lastName": "Kamath",
    "position": "Founder & Managing Partner",
    "image": "https://kpi.co/assets/images/partner-img-4.webp",
    "email": "kamath@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Executive",
  },
  {
    "id": 101,
    "parentId": 100,
    "name": "Aneesh",
    "lastName": "P",
    "position": "Partner Application",
    "image": "https://kpi.co/assets/images/partner-img-2.webp",
    "email": "aneesh@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Application",
  },
  {
    "id": 102,
    "parentId": 100,
    "name": "Mahesh",
    "lastName": "Shetty",
    "position": "Partner - Audit & Assurance",
    "image": "https://kpi.co/assets/images/partner-img-3.webp",
    "email": "mahesh@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Audit & Assurance",

  },
  {
    "id": 103,
    "parentId": 100,
    "name": "Pritesh",
    "lastName": "Kathi",
    "position": "Partner & Chief Operating Officer",
    "image": "https://kpi.co/assets/images/partner-img-5.webp",
    "email": "pritesh@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Executive",

  },
  {
    "id": 104,
    "parentId": 100,
    "name": "Rajgopal",
    "lastName": "Pai",
    "position": "Partner - Advisory",
    "image": "https://kpi.co/assets/images/partner-img-6.webp",
    "email": "pritesh@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Audit & Assurance",

  },
  {
    "id": 105,
    "parentId": 101,
    "name": "Abdul",
    "lastName": "Najeeb",
    "position": "Application Manager",
    "image": "./assets/media/avatars/300-15.jpg",
    "email": "najeeb@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Application",

  },
  {
    "id": 109,
    "parentId": 101,
    "name": "kiran",
    "lastName": "P",
    "position": "Application developer",
    "image": "./assets/media/avatars/300-11.jpg",
    "email": "kiran@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Application",

  },
  {
    "id": 106,
    "parentId": 101,
    "name": "Rekha",
    "lastName": "N",
    "position": "Application developer",
    "image": "./assets/media/avatars/300-26.jpg",
    "email": "rekha@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Application",

  },
  {
    "id": 107,
    "parentId": 101,
    "name": "Neenu",
    "lastName": "A",
    "position": "Application developer",
    "image": "./assets/media/avatars/300-22.jpg",
    "email": "neenu@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Application",

  },
  {
    "id": 108,
    "parentId": 101,
    "name": "Akshay",
    "lastName": "P",
    "position": "UI UX Designer",
    "image": "./assets/media/avatars/300-30.jpg",
    "email": "akshay@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Application",

  },
  {
    "id": 110,
    "parentId": 105,
    "name": "Prashanth",
    "lastName": "K",
    "position": "Application developer",
    "image": "./assets/media/avatars/300-17.jpg",
    "email": "prashanth@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Application",

  },
  {
    "id": 111,
    "parentId": 105,
    "name": "Rachana",
    "lastName": "",
    "position": "Application developer",
    "image": "./assets/media/avatars/300-16.jpg",
    "email": "rachana@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Application",

  },
  {
    "id": 112,
    "parentId": 105,
    "name": "Mahammed",
    "lastName": "Swalih",
    "position": "Application developer",
    "image": "./assets/media/avatars/300-29.jpg",
    "email": "swalih@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Application",

  },
  {
    "id": 113,
    "parentId": 105,
    "name": "Swathi",
    "lastName": "Sharma",
    "position": "Application developer",
    "image": "./assets/media/avatars/300-8.jpg",
    "email": "swathi@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Application",

  },
  {
    "id": 114,
    "parentId": 105,
    "name": "Anjali",
    "lastName": "K",
    "position": "Application developer",
    "image": "./assets/media/avatars/300-12.jpg",
    "email": "anjali@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Application",
  },
  {
    "id": 115,
    "parentId": 108,
    "name": "Prajna",
    "lastName": "A",
    "position": "UI UX Designer",
    "image": "./assets/media/avatars/300-20.jpg",
    "email": "prajna@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Application",

  },
  {
    "id": 116,
    "parentId": 109,
    "name": "C",
    "lastName": "Vyshnav",
    "position": "Junior Application Developer",
    "image": "./assets/media/avatars/300-21.jpg",
    "email": "prajna@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Application",

  },
  {
    "id": 118,
    "parentId": 109,
    "name": "Mahammad",
    "lastName": "Marzook",
    "position": "Junior Application Developer",
    "image": "./assets/media/avatars/300-25.jpg",
    "email": "marzook@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Application",

  },
  {
    "id": 119,
    "parentId": 109,
    "name": "Melroy",
    "lastName": "Joyson Lobo",
    "position": "Junior Application Developer",
    "image": "./assets/media/avatars/300-17.jpg",
    "email": "melroy@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Application",

  },
  {
    "id": 120,
    "parentId": 102,
    "name": "Dinesh",
    "lastName": "Poojary",
    "position": "Supervisor - Audit & Assurance",
    "image": "./assets/media/avatars/300-5.jpg",
    "email": "dinesh@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Audit & Assurance",

  },
  {
    "id": 121,
    "parentId": 120,
    "name": "Suveen",
    "lastName": "Achar",
    "position": "Assistant Manager - Accounts",
    "image": "./assets/media/avatars/300-13.jpg",
    "email": "suveen@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Audit & Assurance",

  },
  {
    "id": 122,
    "parentId": 102,
    "name": "Nisha",
    "lastName": "Kotian",
    "position": "Assistant Manager",
    "image": "./assets/media/avatars/300-14.jpg",
    "email": "nisha@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Audit & Assurance",
  },
  {
    "id": 123,
    "parentId": 103,
    "name": "Aman",
    "lastName": "Kumar Jha",
    "position": "HRMS Lead & Hr Manager",
    "image": "./assets/media/avatars/300-13.jpg",
    "email": "aman@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Human Resources",

  },
  {
    "id": 124,
    "parentId": 123,
    "name": "Revathy",
    "lastName": "VS",
    "position": "Hr Coordinator",
    "image": "./assets/media/avatars/300-22.jpg",
    "email": "revathy@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Human Resources",

  },
  {
    "id": 125,
    "parentId": 103,
    "name": "Santanu",
    "lastName": "Das",
    "position": "Project Manager",
    "image": "./assets/media/avatars/300-30.jpg",
    "email": "santanu@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Application",

  },
  {
    "id": 127,
    "parentId": 105,
    "name": "Arshitha",
    "lastName": "M S",
    "position": "Application Developer",
    "image": "./assets/media/avatars/300-20.jpg",
    "email": "arshitha@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Application",

  },
  {
    "id": 128,
    "parentId": 105,
    "name": "Abhishek",
    "lastName": "P Shenoy",
    "position": "Application Developer",
    "image": "./assets/media/avatars/300-9.jpg",
    "email": "abhishek@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Application",

  },
  {
    "id": 129,
    "parentId": 105,
    "name": "Amrutha",
    "lastName": "B",
    "position": "Application Developer",
    "image": "./assets/media/avatars/300-22.jpg",
    "email": "amrutha@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Application",

  },
  {
    "id": 130,
    "parentId": 105,
    "name": "Andriya",
    "lastName": "Maria D'Costa",
    "position": "Junior Application Developer",
    "image": "./assets/media/avatars/300-6.jpg",
    "email": "andriya@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Application",

  },
  {
    "id": 131,
    "parentId": 105,
    "name": "Cloyd",
    "lastName": "Nikki Hirang",
    "position": "Application Developer",
    "image": "./assets/media/avatars/300-29.jpg",
    "email": "cloyd@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Application",

  },
  {
    "id": 132,
    "parentId": 105,
    "name": "Manish",
    "lastName": "R Shetty",
    "position": " Junior Application Developer",
    "image": "./assets/media/avatars/300-7.jpg",
    "email": "manish@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Application",

  },
  {
    "id": 133,
    "parentId": 105,
    "name": "Naziyz",
    "lastName": "Salma",
    "position": " Junior Application Developer",
    "image": "./assets/media/avatars/300-4.jpg",
    "email": "naziya@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Application",

  },
  {
    "id": 134,
    "parentId": 105,
    "name": "Priyanka",
    "lastName": "Basavaraj Murudeshwar",
    "position": " Junior Application Developer",
    "image": "./assets/media/avatars/300-28.jpg",
    "email": "priyanka@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "India",
    "department": "Application",

  },
  {
    "id": 135,
    "parentId": 101,
    "name": "Jerome",
    "lastName": "Antefar Luckas",
    "position": "Application Developer",
    "image": "./assets/media/avatars/300-9.jpg",
    "email": "jerome@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Application",

  },
  {
    "id": 136,
    "parentId": 101,
    "name": "Najla",
    "lastName": "Polla Pparammal",
    "position": "Application Developer",
    "image": "./assets/media/avatars/300-7.jpg",
    "email": "najla@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Application",

  },
  {
    "id": 137,
    "parentId": 101,
    "name": "Reena",
    "lastName": "Joseph",
    "position": "Senior Application Developer",
    "image": "./assets/media/avatars/300-20.jpg",
    "email": "reena@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Application",

  },
  {
    "id": 138,
    "parentId": 101,
    "name": "Viraja",
    "lastName": "K",
    "position": "Application Developer",
    "image": "./assets/media/avatars/300-27.jpg",
    "email": "viraja@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Application",

  },
  {
    "id": 139,
    "parentId": 101,
    "name": "Reshma",
    "lastName": "Sinu",
    "position": "Senior Application Developer",
    "image": "./assets/media/avatars/300-12.jpg",
    "email": "reshma@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Application",

  },
  {
    "id": 141,
    "parentId": 102,
    "name": "Kabindra",
    "lastName": "Sapkota",
    "position": "Audit Associate",
    "image": "./assets/media/avatars/300-21.jpg",
    "email": "kabindra@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Audit & Assurance",

  },
  {
    "id": 142,
    "parentId": 102,
    "name": "Ramakrishna",
    "lastName": "Reddy",
    "position": "Business Setup Executive",
    "image": "./assets/media/avatars/300-17.jpg",
    "email": "ramakrishna@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Audit & Assurance",

  },
  {
    "id": 143,
    "parentId": 102,
    "name": "Suganth",
    "lastName": "Ramasamy",
    "position": "Supervisor Audit & Assurance",
    "image": "./assets/media/avatars/300-3.jpg",
    "email": "suganth@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Audit & Assurance",

  },
  {
    "id": 144,
    "parentId": 102,
    "name": "Sushil",
    "lastName": "Khandelwal",
    "position": "Director Audit",
    "image": "./assets/media/avatars/300-21.jpg",
    "email": "sushil@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Audit & Assurance",

  },
  {
    "id": 145,
    "parentId": 120,
    "name": "Safoora",
    "lastName": "P",
    "position": "Junior Audit Associate",
    "image": "./assets/media/avatars/300-20.jpg",
    "email": "safoora@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Audit & Assurance",

  },
  {
    "id": 146,
    "parentId": 143,
    "name": "Abdul",
    "lastName": "Ahaad",
    "position": "Audit Associate",
    "image": "./assets/media/avatars/300-9.jpg",
    "email": "ahad@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Audit & Assurance",

  },
  {
    "id": 147,
    "parentId": 143,
    "name": "Ashwin",
    "lastName": "Thomas",
    "position": "Junior Associate",
    "image": "./assets/media/avatars/300-23.jpg",
    "email": "ashwin@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Audit & Assurance",

  },
  {
    "id": 148,
    "parentId": 143,
    "name": "Basim",
    "lastName": "Mohammed",
    "position": "Junior Audit Associate",
    "image": "./assets/media/avatars/300-5.jpg",
    "email": "basim@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Audit & Assurance",

  },
  {
    "id": 149,
    "parentId": 143,
    "name": "Praksh",
    "lastName": "Shetty",
    "position": "Senior Asoociate - Audit & Associate",
    "image": "./assets/media/avatars/300-13.jpg",
    "email": "prakash@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Audit & Assurance",

  },
  {
    "id": 151,
    "parentId": 143,
    "name": "Vijay",
    "lastName": "Pandy",
    "position": "Junior Asoociate",
    "image": "./assets/media/avatars/300-29.jpg",
    "email": "vijay@kpi.co",
    "phone_number": "+971 445 51 010",
    "location": "UAE",
    "department": "Audit & Assurance",

  },
]
const departments = ["Executive","Audit & Assurance","Application","Human Resources"]

const colors = ["#634490","#FF983B","#3466A5","#FE4E4E","#EE5397","#00C4D4","#26465F","#DD5C50","#116178","#FDB956","#003C4D","#B95461","#4F7ABB","#2CBDC2","#B46FC9","#406792","#FE7B47", "#028A46"]

export { orgData , departments, colors};

