apiVersion: v1
kind: Secret
metadata:
   name: {{ index .Values.secrets.names 0 }}
   namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data.secret }}
  {{ $key }}: {{ $value | b64enc -}}
  {{ end }}